language: node_js
node_js:
  - 10.8.0
cache:
  directories:
    - node_modules
branches:
  only:
    - production
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng build --prod --output-path docs --base-href /angularCart/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: docs
  target-branch: master
  on:
    branch: production
